ALTER DATABASE dawa CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(100) NOT NULL,
	email VARCHAR(300) NOT NULL,
	password CHAR(128) NOT NULL, -- CHAR COUNT FOR SHA-512 HEXADECIMAL STRING
	signupDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE administrator (
	id INTEGER PRIMARY KEY,

	FOREIGN KEY(id) REFERENCES user(id)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE client (
	id INTEGER PRIMARY KEY,
	type INTEGER NOT NULL,
	totalExpenses FLOAT NOT NULL,

	FOREIGN KEY(id) REFERENCES user(id)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE product (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(300) NOT NULL,
	price FLOAT NOT NULL,
	stock INTEGER NOT NULL,
	type INTEGER NOT NULL
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE cd (
	id INTEGER PRIMARY KEY,
	title VARCHAR(200) NOT NULL,
	author VARCHAR(200) NULL,
	year YEAR NOT NULL,

	FOREIGN KEY(id) REFERENCES product(id)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE cactus (
	id INTEGER PRIMARY KEY,
	species VARCHAR(200) NOT NULL,
	origin VARCHAR(200) NULL,

	FOREIGN KEY(id) REFERENCES product(id)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `order` (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	finalPrice FLOAT NOT NULL,
	date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	discount FLOAT NOT NULL,
	client INTEGER NULL,

	FOREIGN KEY(client) REFERENCES client(id)
		ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE orderLine (
	`order` INTEGER NOT NULL,
	lineNumber INTEGER NOT NULL,
	product INTEGER NULL,
	quantity INTEGER NOT NULL,
	unitPrice FLOAT NOT NULL,

	FOREIGN KEY(product) REFERENCES product(id)
		ON DELETE SET NULL ON UPDATE CASCADE,

	FOREIGN KEY(`order`) REFERENCES `order`(id)
		ON DELETE CASCADE ON UPDATE CASCADE,

	PRIMARY KEY(`order`, lineNumber)
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE rating (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	product INTEGER NOT NULL,
	client INTEGER NOT NULL,
	value FLOAT NOT NULL,
	date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY(product) REFERENCES product(id)
		ON DELETE CASCADE ON UPDATE CASCADE,

	FOREIGN KEY(client) REFERENCES client(id)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE comment (
	rating INTEGER PRIMARY KEY,
	title VARCHAR(200) NOT NULL,
	content TEXT NOT NULL,

	FOREIGN KEY(rating) REFERENCES rating(id)
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


DELIMITER '$';

CREATE PROCEDURE changePassword (IN password CHAR(128), IN username VARCHAR(100), IN oldPassword CHAR(128))
BEGIN
    UPDATE user SET password = SHA2(password, 512) WHERE username = username AND password = SHA2(oldPassword, 512);
END$

CREATE PROCEDURE fetchUser(IN userID INTEGER)
BEGIN
    SELECT * FROM user WHERE id = userID;
END$

CREATE PROCEDURE updateClientExpenses(IN userID INTEGER, IN totalExpenses FLOAT, IN type INTEGER)
BEGIN
    UPDATE client SET totalExpenses = totalExpenses, type = type WHERE id = userID;
END$

DELIMITER ';'$